#!/usr/bin/env bash 
set -e

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="sushilraje/azureiot/pcs-config-dotnet"
# "testing" is the latest dev build, usually matching the code in the "master" branch
DOCKER_TAG="$DOCKER_IMAGE:adm"

docker push $DOCKER_TAG
