#!/usr/bin/env bash

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/pcs-auth-dotnet"

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

# The version is stored in a file, to avoid hardcoding it in multiple places
APP_VERSION=$(cat "$APP_HOME/version")

run_container() {
    check_dependency_docker

    $APP_HOME/scripts/env-vars-check

    # Some settings are used to connect to an external dependency, e.g. Azure IoT Hub and IoT Hub Manager API
    # Depending on which settings and which dependencies are needed, edit the list of variables
    echo "Starting Auth ..."
    docker run -it -p 9001:9001 \
        -e "PCS_AUTH_AAD_GLOBAL_TENANTID=$PCS_AUTH_AAD_GLOBAL_TENANTID" \
        -e "PCS_AUTH_AAD_GLOBAL_CLIENTID=$PCS_AUTH_AAD_GLOBAL_CLIENTID" \
        -e "PCS_AUTH_AAD_GLOBAL_LOGINURI=$PCS_AUTH_AAD_GLOBAL_LOGINURI" \
        "$DOCKER_IMAGE:$APP_VERSION"
}

run_container

set +e
