FROM microsoft/aspnetcore-build:2.0-jessie
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

EXPOSE 9024

WORKDIR /src
COPY ["remote-monitoring.sln", "./"]
COPY ["asa-manager/DeviceGroupsAgent/DeviceGroupsAgent.csproj", "asa-manager/DeviceGroupsAgent/"]
COPY ["asa-manager/Services/Services.csproj", "asa-manager/Services/"]
COPY ["asa-manager/SetupAgent/SetupAgent.csproj", "asa-manager/SetupAgent/"]
COPY ["asa-manager/TelemetryRulesAgent/TelemetryRulesAgent.csproj", "asa-manager/TelemetryRulesAgent/"]
COPY ["asa-manager/WebService/WebService.csproj", "asa-manager/WebService/"]
COPY ["asa-manager/WebService/azds_entrypoint.sh", "asa-manager/WebService/azds_entrypoint.sh"]

RUN chmod 777 /src/asa-manager/WebService/azds_entrypoint.sh
RUN dotnet restore -nowarn:msb3202,nu1503
COPY . .
WORKDIR "/src/asa-manager/WebService"
RUN dotnet build "WebService.csproj"

ENTRYPOINT  ["sh", "/src/asa-manager/WebService/azds_entrypoint.sh"]