#!/usr/bin/env bash

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/iothub-manager-dotnet"

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

# The version is stored in a file, to avoid hardcoding it in multiple places
APP_VERSION=$(cat "$APP_HOME/version")

run_container() {
    check_dependency_docker

    $APP_HOME/scripts/env-vars-check

	echo "Starting IoT Hub Manager ..."
	docker run -it -p 9002:9002 \
        -e "PCS_IOTHUB_CONNSTRING=$PCS_IOTHUB_CONNSTRING" \
        -e "PCS_CONFIG_WEBSERVICE_URL=$PCS_CONFIG_WEBSERVICE_URL" \
        "$DOCKER_IMAGE:$APP_VERSION"
}

run_container

set +e
