#!/usr/bin/env bash

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/iothub-manager-dotnet"

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

# The version is stored in a file, to avoid hardcoding it in multiple places
APP_VERSION=$(cat "$APP_HOME/version")

run_container() {
    check_dependency_docker

    $APP_HOME/scripts/env-vars-check

	echo "Starting IoT Hub Manager ..."
	docker run -it -p $PCS_IOTHUBMANAGER_WEBSERVICE_PORT:$PCS_IOTHUBMANAGER_WEBSERVICE_PORT \
        -e "PCS_IOTHUBMANAGER_WEBSERVICE_PORT=$PCS_IOTHUBMANAGER_WEBSERVICE_PORT" \
        -e "PCS_IOTHUB_CONN_STRING=$PCS_IOTHUB_CONN_STRING" \
        "$DOCKER_IMAGE:$APP_VERSION"
}

run_container

set +e
